// import {Inter} from "next/font/google";
// import Topbar from "@/app/topbar";
//
// const inter = Inter({subsets: ["latin"]});
//
// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };
//
// export default function Template({children}: { children: React.ReactNode }) {
//     return (
//         <>
//             <Topbar/>
//             <div>{children}</div>
//         </>
//     )
// }
