import { Inter } from "next/font/google";

import "../styles/style.module.css";
import "../styles/datatables.min.css";
import "../styles/ti.css";
import "../styles/loader-0.module.css";
import "../styles/vendor.bundle.css";
import "../styles/fa.module.css";
import TopBar from "@/app/admin/top-bar";
import Footer from "@/app/admin/footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <TopBar />
            <div>{children}</div>
            <Footer/>
        </>
    );
}
