import {Inter} from "next/font/google";
import Footer from "@/app/admin/footer";
import TopBar from "@/app/admin/top-bar";

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Template({ children }: { children: React.ReactNode }) {
    return (
        <>
            <TopBar />
            <div>{children}</div>
            <Footer/>
        </>
    )
}
